version: "3"

services:
  postgres:
    image: postgres:13.2
    volumes:
      - ./src/test/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bonus-accrual
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24